/**
 * Grandturk/cockburn API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CockburnASRSegmentPayload } from './cockburnASRSegmentPayload';


export interface CockburnClipPayload { 
    s3Fileapth?: string;
    segments?: Array<CockburnASRSegmentPayload>;
}

