/**
 * Grandturk/cockburn API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CockburnClipPayload } from './cockburnClipPayload';
import { CockburnTypeTranscribeStatus } from './cockburnTypeTranscribeStatus';


export interface CockburnGetTranscribeResponse { 
    projectId?: string;
    transcriptionId?: string;
    status?: CockburnTypeTranscribeStatus;
    payload?: CockburnClipPayload;
}
export namespace CockburnGetTranscribeResponse {
}


