/**
 * Grandturk/cockburn API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CockburnTypeEngine = 'TYPE_ENGINE_UNSPECIFIED' | 'TYPE_ENGINE_ASR_OPENAIWHISPER' | 'TYPE_ENGINE_ASR_WHISPERCPP' | 'TYPE_ENGINE_ASR_FASTERWHISPER';

export const CockburnTypeEngine = {
    Unspecified: 'TYPE_ENGINE_UNSPECIFIED' as CockburnTypeEngine,
    AsrOpenaiwhisper: 'TYPE_ENGINE_ASR_OPENAIWHISPER' as CockburnTypeEngine,
    AsrWhispercpp: 'TYPE_ENGINE_ASR_WHISPERCPP' as CockburnTypeEngine,
    AsrFasterwhisper: 'TYPE_ENGINE_ASR_FASTERWHISPER' as CockburnTypeEngine
};

