/**
 * Grandturk/cockburn API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CockburnTypeTranscribeStatus = 'TYPE_TRANSCRIBE_STATUS_UNSPECIFIED' | 'TYPE_TRANSCRIBE_STATUS_CREATED' | 'TYPE_TRANSCRIBE_STATUS_SCHEDILED' | 'TYPE_TRANSCRIBE_STATUS_PENDING' | 'TYPE_TRANSCRIBE_STATUS_RUNNING' | 'TYPE_TRANSCRIBE_STATUS_FINISHED' | 'TYPE_TRANSCRIBE_STATUS_FAILED';

export const CockburnTypeTranscribeStatus = {
    Unspecified: 'TYPE_TRANSCRIBE_STATUS_UNSPECIFIED' as CockburnTypeTranscribeStatus,
    Created: 'TYPE_TRANSCRIBE_STATUS_CREATED' as CockburnTypeTranscribeStatus,
    Schediled: 'TYPE_TRANSCRIBE_STATUS_SCHEDILED' as CockburnTypeTranscribeStatus,
    Pending: 'TYPE_TRANSCRIBE_STATUS_PENDING' as CockburnTypeTranscribeStatus,
    Running: 'TYPE_TRANSCRIBE_STATUS_RUNNING' as CockburnTypeTranscribeStatus,
    Finished: 'TYPE_TRANSCRIBE_STATUS_FINISHED' as CockburnTypeTranscribeStatus,
    Failed: 'TYPE_TRANSCRIBE_STATUS_FAILED' as CockburnTypeTranscribeStatus
};

