/**
 * Grandturk/cockburn API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CockburnAppOauth2LoginResponse } from './cockburnAppOauth2LoginResponse';
import { CockburnAppBasicLoginResponse } from './cockburnAppBasicLoginResponse';


export interface CockburnAppLoginResponse { 
    basic?: CockburnAppBasicLoginResponse;
    oauth2?: CockburnAppOauth2LoginResponse;
}

