/**
 * Grandturk/cockburn API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserstoreApplicationID = 'APPLICATION_ID_UNSPECIFIED' | 'APPLICATION_ID_KAFEIDO';

export const UserstoreApplicationID = {
    Unspecified: 'APPLICATION_ID_UNSPECIFIED' as UserstoreApplicationID,
    Kafeido: 'APPLICATION_ID_KAFEIDO' as UserstoreApplicationID
};

